### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by csteele2** [LarissaReames-NOAA/MPASSIT#22]
Is this meant to be an internal tool for NOAA or something for the community to use? If the latter, I think the docs/instructions might need some attention, as 1) edit build.sh 2) run build.sh are perhaps maybe a little lacking? From what I gather, I might need to edit machine-setup.sh and make a modulefile in modulefiles as well?

**Comment by LarissaReames-NOAA** [comment]
Caleb,

You're right, it's been a little lacking. I meant to get more information in to the documentation before my presentation at WRF-MPAS a couple weeks ago but I wasn't able to. I've tried to answer some of these questions in my latest PR (#23). Feel free to look at what I've added and provide some feedback on that PR if you'd like to see some more information.

**Comment by csteele2** [comment]
Awesome, thanks! I know documentation is not fun and takes some time. I reached the end of my patience trying to process data natively. Thanks again for the work and sharing!

**Comment by LarissaReames-NOAA** [comment]
Hi @csteele2 I went ahead and merged those changes in #23 . Do you still need some additional instruction there or can I go ahead and close this issue?

**Comment by csteele2** [comment]
Honestly, I have hit so so many roadblocks with MPAS, and inability to replicate WRF functionality, I have pretty much put a pin in any MPAS development. I had tried that PR, and I think the only roadblock was my unfamiliarity with modules (which everyone is using now, so that's on me). We can close it.
