### ISSUE TITLE
Can't build MPASSIT on Hera

### ISSUE THREAD

**Issue by EricJames-NOAA** [LarissaReames-NOAA/MPASSIT#35]
I can't build MPASSIT on Hera following the instructions on Github.  Looks like the build.hera.intel.lua modulefile is quite a bit older than the Jet one...maybe it needs to be updated?  I'm happy to help with this, just checking to see if anyone else has run into this issue.  

Thanks

**Comment by JiliDong-NOAA** [comment]
This is what I do on Hera for compiling MPASSIT:

1. load modules:

module purge
module use /scratch1/NCEPDEV/fv3-cam/Jili.Dong/mpas/sorc/modulefiles
module load ufs_hera.intel
setenv PNETCDF /apps/pnetcdf/1.12.3/intel_2023.2.0-impi/

2. comment out L33-35 in build.sh:

#    module use ./modulefiles
#    module load build.$target.$compiler.lua
#    module list

3. build.sh hera intel

Works fine so far. I think some modules need to be updated in modulefiles/build.hera.intel.lua. 

Hope this helps.

**Comment by EricJames-NOAA** [comment]
@JiliDong-NOAA thank you for the help!  That works for me too!

**Comment by LarissaReames-NOAA** [comment]
Closed as addressed with #36
